from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
import urllib.request
import urllib.error

app = FastAPI(title="Galaxy Package Registry", description="Official package manager registry for Nova")

# Dummy database for now until Supabase is connected
MOCK_DB = {
    "nova-http": {
        "repo": "nova-programming/nova-http",
        "description": "High-performance HTTP client for REST APIs. Compiles natively to C-level sockets.",
        "version": "1.0.2",
        "author": "Nova Core Team",
        "tags": ["network", "http", "api"]
    },
    "nova-math": {
        "repo": "nova-programming/nova-math",
        "description": "Fast cryptographic functions, ChaCha20 PRNG helpers, and advanced linear algebra structs.",
        "version": "0.9.5",
        "author": "Nova Core Team",
        "tags": ["crypto", "math", "random"]
    }
}

MOCK_MARKDOWN = """
# {package_name}

{description}

## Installation

You can install this package globally using the Galaxy package manager:

```bash
nova galaxy install {package_name}
```

## Quick Start

Here is a simple example of how to use this library in your Nova code:

```nova
import {package_name}

def main() {
    print("Successfully imported {package_name}!")
}
```

## API Reference

### Core Functions

- `init()`: Initializes the module.
- `execute(task)`: Runs the main process.

> **Note**: This is a mock readme dynamically generated by the Galaxy Registry until the actual GitHub repository is fully populated with documentation!
"""

class PublishRequest(BaseModel):
    package_name: str
    github_repo: str

@app.get("/", response_class=HTMLResponse)
def read_root():
    try:
        with open("templates/index.html", "r") as f:
            html_content = f.read()
        return HTMLResponse(content=html_content, status_code=200)
    except FileNotFoundError:
        return HTMLResponse(content="<h1>Galaxy Registry Online</h1>", status_code=200)

@app.get("/api/packages")
def list_packages():
    # Return a summary of all packages
    packages = []
    for name, data in MOCK_DB.items():
        packages.append({
            "name": name,
            "description": data["description"],
            "version": data["version"],
            "tags": data["tags"]
        })
    return {"packages": packages}

@app.get("/api/packages/{package_name}")
def get_package(package_name: str):
    data = MOCK_DB.get(package_name)
    if not data:
        raise HTTPException(status_code=404, detail="Package not found")
    
    repo = data["repo"]
    readme_url = f"https://raw.githubusercontent.com/{repo}/main/README.md"
    
    # Try fetching the real readme, fallback to mock if 404
    readme_content = ""
    try:
        req = urllib.request.Request(readme_url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req) as response:
            readme_content = response.read().decode('utf-8')
    except urllib.error.URLError:
        readme_content = MOCK_MARKDOWN.replace("{package_name}", package_name).replace("{description}", data["description"])
        
    return {
        "package": package_name,
        "github_repo": repo,
        "version": data["version"],
        "author": data["author"],
        "description": data["description"],
        "tags": data["tags"],
        "readme": readme_content,
        "download_url": f"https://github.com/{repo}/archive/refs/heads/main.zip"
    }

@app.post("/api/publish")
def publish_package(req: PublishRequest):
    # TODO: Insert into Supabase
    MOCK_DB[req.package_name] = {
        "repo": req.github_repo,
        "description": "A new Nova package.",
        "version": "0.1.0",
        "author": "Community",
        "tags": []
    }
    return {"status": "success", "message": f"Successfully registered {req.package_name}"}
